services:
  # ==========================================
  # [网络层] Cloudflare 穿透隧道 (全球极速访问)
  # ==========================================
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare_tunnel
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CF_TUNNEL_TOKEN}

  # ----------------------------------------
  # 调度中枢: API Gateway & PWA
  # ----------------------------------------
  gateway:
    build:
      context: ./gateway
    container_name: api_gateway
    ports:
      - "5000:5000"
    volumes:
      - ./gateway/app:/app
    restart: unless-stopped

  # ==========================================
  # GPU 0 (7900 XTX): vLLM 推理引擎 (2026 SOTA 架构)
  # ==========================================
  vllm-qwen:
    image: vllm/vllm-openai-rocm:latest #for support of --reasoning-config, it gets dropped on latest nightly
    container_name: vllm_qwen
    ports:
      - "8000:8000"
    devices:
      - "/dev/kfd:/dev/kfd"
      - "/dev/dri:/dev/dri"
    group_add:
      - video
      - render
    environment:
      - HIP_VISIBLE_DEVICES=0
      - VLLM_USE_TRITON_AWQ=1
      - FLASH_ATTENTION_TRITON_AMD_ENABLE=TRUE
      - HUGGING_FACE_HUB_TOKEN=${HF_TOKEN}
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
      - ./qwen3.5/thinking.jinja:/app/thinking.jinja
    entrypoint: []
    # 【关键修复 2】：手动指定 bash 执行环境
    command: >
      vllm serve groxaxo/Qwen3.6-27B-GPTQ-Pro-4bit
      --dtype float16
      --disable-custom-all-reduce
      --max-model-len 8192
      --gpu-memory-utilization 0.99
      --language-model-only
      --max-num-seqs 80
      --chat-template /app/thinking.jinja
      --served-model-name qwen3
      --trust-remote-code
    restart: unless-stopped

 # ==========================================
# 文件名: docker-compose.audio.yml
# 架构定位: GPU 1 (7800 XT) - 纯正 ROCm 原生听觉与发声节点
# ==========================================
  qwen3-asr:
    build:
        context: ./qwen3-asr
    container_name: qwen3_asr
    ports:
      - "9000:8000"
    devices:
      - "/dev/kfd:/dev/kfd"
      - "/dev/dri:/dev/dri"
    group_add:
      - video
      - render
    environment:
      - HIP_VISIBLE_DEVICES=1
      - VLLM_USE_TRITON_AWQ=1
      - HUGGING_FACE_HUB_TOKEN=${HF_TOKEN}
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    entrypoint: []
    # 【关键修复 2】：手动指定 bash 执行环境
    command: >
      vllm serve Qwen/Qwen3-ASR-1.7B     
      --dtype float16
      --max-model-len 8192
      --gpu-memory-utilization 0.85
      --max-num-seqs 80
      --served-model-name qwen3-asr
      --trust-remote-code
    restart: unless-stopped
