// ==========================================
// 文件名: resources/i18n.js
// 架构定位: [Phase 5] 全局多语言静态字典与渲染引擎
// ==========================================

const SUPPORTED_LANGS = [
    {v: "zh", n: "中文 (zh)"}, {v: "en", n: "English (en)"}, {v: "yue", n: "粤语 (yue)"},
    {v: "ar", n: "العربية (ar)"}, {v: "de", n: "Deutsch (de)"}, {v: "fr", n: "Français (fr)"},
    {v: "es", n: "Español (es)"}, {v: "pt", n: "Português (pt)"}, {v: "id", n: "Bahasa Indonesia (id)"},
    {v: "it", n: "Italiano (it)"}, {v: "ko", n: "한국어 (ko)"}, {v: "ru", n: "Русский (ru)"},
    {v: "th", n: "ไทย (th)"}, {v: "vi", n: "Tiếng Việt (vi)"}, {v: "ja", n: "日本語 (ja)"},
    {v: "tr", n: "Türkçe (tr)"}, {v: "hi", n: "हिन्दी (hi)"}, {v: "ms", n: "Bahasa Melayu (ms)"},
    {v: "nl", n: "Nederlands (nl)"}, {v: "sv", n: "Svenska (sv)"}, {v: "da", n: "Dansk (da)"},
    {v: "fi", n: "Suomi (fi)"}, {v: "pl", n: "Polski (pl)"}, {v: "cs", n: "Čeština (cs)"},
    {v: "fil", n: "Filipino (fil)"}, {v: "fa", n: "فارسی (fa)"}, {v: "el", n: "Ελληνικά (el)"},
    {v: "hu", n: "Magyar (hu)"}, {v: "mk", n: "Македонски (mk)"}, {v: "ro", n: "Română (ro)"}
];

const I18N_DICT = {
    "zh": { title: "🗣️ 随身翻译", btn_start: "🎙️", status_sleep: "💤 待机中", status_listen: "👂 倾听中...", status_capture: "🎙️ 录音中...", status_speak: "🔊 播放中...", tab_trans: "同传", tab_tutor: "外教", tab_admin: "设置", hint_encrypted: "对话已端到端加密，记录仅保存在本地", btn_native_on: "💡 双语教学: 开", btn_native_off: "💡 双语教学: 关", title_tutor: "👨‍🏫 AI 外教", status_speak_tutor: "🔊 讲话中 (可随时打断)..." },
    "en": { title: "🗣️ Translator", btn_start: "🎙️", status_sleep: "💤 Standby", status_listen: "👂 Listening...", status_capture: "🎙️ Recording...", status_speak: "🔊 Speaking...", tab_trans: "Translate", tab_tutor: "Tutor", tab_admin: "Settings", hint_encrypted: "Chats encrypted, history saved locally", btn_native_on: "💡 Bilingual Mode: On", btn_native_off: "💡 Bilingual Mode: Off", title_tutor: "👨‍🏫 AI Tutor", status_speak_tutor: "🔊 Speaking (Interruptible)..." },
    "yue": { title: "🗣️ 隨身翻譯", btn_start: "🎙️", status_sleep: "💤 待機中", status_listen: "👂 聆聽中...", status_capture: "🎙️ 錄音中...", status_speak: "🔊 播放中...", tab_trans: "同傳", tab_tutor: "外教", tab_admin: "設定", hint_encrypted: "對話已加密，歷史記錄僅保存在本地", btn_native_on: "💡 雙語教學: 開", btn_native_off: "💡 雙語教學: 關", title_tutor: "👨‍🏫 AI 外教", status_speak_tutor: "🔊 講話中 (可隨時打斷)..." },
    "ar": { title: "🗣️ المترجم", btn_start: "🎙️", status_sleep: "💤 وضع الاستعداد", status_listen: "👂 يستمع...", status_capture: "🎙️ يسجل...", status_speak: "🔊 يتحدث...", tab_trans: "ترجمة", tab_tutor: "معلم", tab_admin: "إعدادات", hint_encrypted: "المحادثات مشفرة، السجل محلي", btn_native_on: "💡 وضع ثنائي اللغة: تشغيل", btn_native_off: "💡 وضع ثنائي اللغة: إيقاف", title_tutor: "👨‍🏫 المعلم الذكي", status_speak_tutor: "🔊 يتحدث (يمكنك المقاطعة)..." },
    "de": { title: "🗣️ Übersetzer", btn_start: "🎙️", status_sleep: "💤 Bereit", status_listen: "👂 Hört zu...", status_capture: "🎙️ Nimmt auf...", status_speak: "🔊 Spricht...", tab_trans: "Übersetzen", tab_tutor: "Tutor", tab_admin: "Einst.", hint_encrypted: "Chats verschlüsselt, Verlauf lokal", btn_native_on: "💡 Zweisprachig: An", btn_native_off: "💡 Zweisprachig: Aus", title_tutor: "👨‍🏫 KI-Tutor", status_speak_tutor: "🔊 Spricht (Unterbrechen möglich)..." },
    "fr": { title: "🗣️ Traducteur", btn_start: "🎙️", status_sleep: "💤 En attente", status_listen: "👂 Écoute...", status_capture: "🎙️ Enregistrement...", status_speak: "🔊 Parle...", tab_trans: "Traduction", tab_tutor: "Prof", tab_admin: "Réglages", hint_encrypted: "Chats chiffrés, historique local", btn_native_on: "💡 Mode Bilingue : ON", btn_native_off: "💡 Mode Bilingue : OFF", title_tutor: "👨‍🏫 Prof IA", status_speak_tutor: "🔊 Parle (Interruption possible)..." },
    "es": { title: "🗣️ Traductor", btn_start: "🎙️", status_sleep: "💤 En espera", status_listen: "👂 Escuchando...", status_capture: "🎙️ Grabando...", status_speak: "🔊 Hablando...", tab_trans: "Traducir", tab_tutor: "Tutor", tab_admin: "Ajustes", hint_encrypted: "Chats cifrados, historial local", btn_native_on: "💡 Modo Bilingüe: ON", btn_native_off: "💡 Modo Bilingüe: OFF", title_tutor: "👨‍🏫 Tutor IA", status_speak_tutor: "🔊 Hablando (Puede interrumpir)..." },
    "pt": { title: "🗣️ Tradutor", btn_start: "🎙️", status_sleep: "💤 Em espera", status_listen: "👂 Ouvindo...", status_capture: "🎙️ Gravando...", status_speak: "🔊 Falando...", tab_trans: "Traduzir", tab_tutor: "Tutor", tab_admin: "Ajustes", hint_encrypted: "Chats criptografados, histórico local", btn_native_on: "💡 Modo Bilíngue: ON", btn_native_off: "💡 Modo Bilíngue: OFF", title_tutor: "👨‍🏫 Tutor IA", status_speak_tutor: "🔊 Falando (Pode interromper)..." },
    "id": { title: "🗣️ Penerjemah", btn_start: "🎙️", status_sleep: "💤 Siap sedia", status_listen: "👂 Mendengarkan...", status_capture: "🎙️ Merekam...", status_speak: "🔊 Berbicara...", tab_trans: "Terjemahan", tab_tutor: "Tutor", tab_admin: "Pengaturan", hint_encrypted: "Obrolan dienkripsi, riwayat lokal", btn_native_on: "💡 Mode Dwibahasa: Nyala", btn_native_off: "💡 Mode Dwibahasa: Mati", title_tutor: "👨‍🏫 Tutor AI", status_speak_tutor: "🔊 Berbicara (Bisa disela)..." },
    "it": { title: "🗣️ Traduttore", btn_start: "🎙️", status_sleep: "💤 In attesa", status_listen: "👂 Ascoltando...", status_capture: "🎙️ Registrazione...", status_speak: "🔊 Parlando...", tab_trans: "Traduci", tab_tutor: "Tutor", tab_admin: "Impost.", hint_encrypted: "Chat crittografate, cronologia locale", btn_native_on: "💡 Modo Bilingue: ON", btn_native_off: "💡 Modo Bilingue: OFF", title_tutor: "👨‍🏫 Tutor IA", status_speak_tutor: "🔊 Parlando (Interrompibile)..." },
    "ko": { title: "🗣️ 번역기", btn_start: "🎙️", status_sleep: "💤 대기 중", status_listen: "👂 듣는 중...", status_capture: "🎙️ 녹음 중...", status_speak: "🔊 재생 중...", tab_trans: "번역", tab_tutor: "튜터", tab_admin: "설정", hint_encrypted: "대화 암호화됨, 기록 로컬 저장", btn_native_on: "💡 이중언어 모드: 켜짐", btn_native_off: "💡 이중언어 모드: 꺼짐", title_tutor: "👨‍🏫 AI 튜터", status_speak_tutor: "🔊 말하는 중 (끼어들기 가능)..." },
    "ru": { title: "🗣️ Переводчик", btn_start: "🎙️", status_sleep: "💤 Ожидание", status_listen: "👂 Слушаю...", status_capture: "🎙️ Запись...", status_speak: "🔊 Говорю...", tab_trans: "Перевод", tab_tutor: "Репетитор", tab_admin: "Настройки", hint_encrypted: "Чаты зашифрованы, история локальна", btn_native_on: "💡 Двуязычный режим: Вкл", btn_native_off: "💡 Двуязычный режим: Выкл", title_tutor: "👨‍🏫 ИИ-Репетитор", status_speak_tutor: "🔊 Говорю (Можно перебить)..." },
    "th": { title: "🗣️ นักแปล", btn_start: "🎙️", status_sleep: "💤 สแตนด์บาย", status_listen: "👂 กำลังฟัง...", status_capture: "🎙️ กำลังบันทึก...", status_speak: "🔊 กำลังพูด...", tab_trans: "แปล", tab_tutor: "ติวเตอร์", tab_admin: "ตั้งค่า", hint_encrypted: "แชทเข้ารหัส ประวัติบันทึกในเครื่อง", btn_native_on: "💡 โหมดสองภาษา: เปิด", btn_native_off: "💡 โหมดสองภาษา: ปิด", title_tutor: "👨‍🏫 AI ติวเตอร์", status_speak_tutor: "🔊 กำลังพูด (พูดแทรกได้)..." },
    "vi": { title: "🗣️ Trình dịch", btn_start: "🎙️", status_sleep: "💤 Sẵn sàng", status_listen: "👂 Đang nghe...", status_capture: "🎙️ Đang thu...", status_speak: "🔊 Đang nói...", tab_trans: "Dịch", tab_tutor: "Gia sư", tab_admin: "Cài đặt", hint_encrypted: "Chat được mã hóa, lịch sử lưu cục bộ", btn_native_on: "💡 Chế độ Song ngữ: Bật", btn_native_off: "💡 Chế độ Song ngữ: Tắt", title_tutor: "👨‍🏫 Gia sư AI", status_speak_tutor: "🔊 Đang nói (Có thể ngắt lời)..." },
    "ja": { title: "🗣️ 翻訳機", btn_start: "🎙️", status_sleep: "💤 待機中", status_listen: "👂 リスニング...", status_capture: "🎙️ 録音中...", status_speak: "🔊 再生中...", tab_trans: "翻訳", tab_tutor: "講師", tab_admin: "設定", hint_encrypted: "チャット暗号化済、履歴はローカル保存", btn_native_on: "💡 バイリンガルモード: オン", btn_native_off: "💡 バイリンガルモード: オフ", title_tutor: "👨‍🏫 AI 講師", status_speak_tutor: "🔊 再生中 (割り込み可能)..." },
    "tr": { title: "🗣️ Çevirmen", btn_start: "🎙️", status_sleep: "💤 Beklemede", status_listen: "👂 Dinleniyor...", status_capture: "🎙️ Kaydediliyor...", status_speak: "🔊 Konuşuluyor...", tab_trans: "Çeviri", tab_tutor: "Eğitmen", tab_admin: "Ayarlar", hint_encrypted: "Sohbetler şifreli, geçmiş yerel", btn_native_on: "💡 İki Dilli Mod: Açık", btn_native_off: "💡 İki Dilli Mod: Kapalı", title_tutor: "👨‍🏫 Yapay Zeka Eğitmeni", status_speak_tutor: "🔊 Konuşuluyor (Söze girilebilir)..." },
    "hi": { title: "🗣️ अनुवादक", btn_start: "🎙️", status_sleep: "💤 तैयार", status_listen: "👂 सुन रहा है...", status_capture: "🎙️ रिकॉर्डिंग...", status_speak: "🔊 बोल रहा है...", tab_trans: "अनुवाद", tab_tutor: "शिक्षक", tab_admin: "सेटिंग्स", hint_encrypted: "चैट एन्क्रिप्टेड, इतिहास स्थानीय", btn_native_on: "💡 द्विभाषी मोड: चालू", btn_native_off: "💡 द्विभाषी मोड: बंद", title_tutor: "👨‍🏫 AI ट्यूटर", status_speak_tutor: "🔊 बोल रहा है (बीच में टोकें)..." },
    "ms": { title: "🗣️ Penterjemah", btn_start: "🎙️", status_sleep: "💤 Sedia", status_listen: "👂 Mendengar...", status_capture: "🎙️ Merakam...", status_speak: "🔊 Bercakap...", tab_trans: "Terjemah", tab_tutor: "Tutor", tab_admin: "Tetapan", hint_encrypted: "Sembang disulitkan, sejarah tempatan", btn_native_on: "💡 Mod Dwibahasa: Hidup", btn_native_off: "💡 Mod Dwibahasa: Mati", title_tutor: "👨‍🏫 Tutor AI", status_speak_tutor: "🔊 Bercakap (Boleh sampuk)..." },
    "nl": { title: "🗣️ Vertaler", btn_start: "🎙️", status_sleep: "💤 Stand-by", status_listen: "👂 Luisteren...", status_capture: "🎙️ Opnemen...", status_speak: "🔊 Spreken...", tab_trans: "Vertalen", tab_tutor: "Docent", tab_admin: "Instellingen", hint_encrypted: "Chats versleuteld, lokale geschiedenis", btn_native_on: "💡 Tweetalige Modus: Aan", btn_native_off: "💡 Tweetalige Modus: Uit", title_tutor: "👨‍🏫 AI Docent", status_speak_tutor: "🔊 Spreken (Onderbreken mogelijk)..." },
    "sv": { title: "🗣️ Översättare", btn_start: "🎙️", status_sleep: "💤 Redo", status_listen: "👂 Lyssnar...", status_capture: "🎙️ Spelar in...", status_speak: "🔊 Talar...", tab_trans: "Översätt", tab_tutor: "Lärare", tab_admin: "Inställningar", hint_encrypted: "Chattar krypterade, lokal historik", btn_native_on: "💡 Tvåspråkigt Läge: På", btn_native_off: "💡 Tvåspråkigt Läge: Av", title_tutor: "👨‍🏫 AI Lärare", status_speak_tutor: "🔊 Talar (Avbrytbar)..." },
    "da": { title: "🗣️ Oversætter", btn_start: "🎙️", status_sleep: "💤 Klar", status_listen: "👂 Lytter...", status_capture: "🎙️ Optager...", status_speak: "🔊 Taler...", tab_trans: "Oversæt", tab_tutor: "Tutor", tab_admin: "Indstillinger", hint_encrypted: "Chats krypteret, lokal historik", btn_native_on: "💡 Tosproget Tilstand: Til", btn_native_off: "💡 Tosproget Tilstand: Fra", title_tutor: "👨‍🏫 AI Tutor", status_speak_tutor: "🔊 Taler (Kan afbrydes)..." },
    "fi": { title: "🗣️ Kääntäjä", btn_start: "🎙️", status_sleep: "💤 Valmiina", status_listen: "👂 Kuunnellaan...", status_capture: "🎙️ Nauhoitetaan...", status_speak: "🔊 Puhutaan...", tab_trans: "Käännä", tab_tutor: "Opettaja", tab_admin: "Asetukset", hint_encrypted: "Chatit salattu, paikallinen historia", btn_native_on: "💡 Kaksikielinen Tila: Päällä", btn_native_off: "💡 Kaksikielinen Tila: Pois", title_tutor: "👨‍🏫 AI Opettaja", status_speak_tutor: "🔊 Puhuu (Keskeytettävissä)..." },
    "pl": { title: "🗣️ Tłumacz", btn_start: "🎙️", status_sleep: "💤 Gotowy", status_listen: "👂 Słuchanie...", status_capture: "🎙️ Nagrywanie...", status_speak: "🔊 Mówienie...", tab_trans: "Tłumacz", tab_tutor: "Nauczyciel", tab_admin: "Ustawienia", hint_encrypted: "Czaty zaszyfrowane, historia lokalna", btn_native_on: "💡 Tryb Dwujęzyczny: Wł", btn_native_off: "💡 Tryb Dwujęzyczny: Wył", title_tutor: "👨‍🏫 Nauczyciel AI", status_speak_tutor: "🔊 Mówi (Można przerwać)..." },
    "cs": { title: "🗣️ Překladatel", btn_start: "🎙️", status_sleep: "💤 Připraven", status_listen: "👂 Poslouchám...", status_capture: "🎙️ Nahrávání...", status_speak: "🔊 Mluvím...", tab_trans: "Překlad", tab_tutor: "Lektor", tab_admin: "Nastavení", hint_encrypted: "Chaty šifrovány, lokální historie", btn_native_on: "💡 Bilingvní Režim: Zap", btn_native_off: "💡 Bilingvní Režim: Vyp", title_tutor: "👨‍🏫 AI Lektor", status_speak_tutor: "🔊 Mluví (Lze přerušit)..." },
    "fil": { title: "🗣️ Tagasalin", btn_start: "🎙️", status_sleep: "💤 Standby", status_listen: "👂 Nakikinig...", status_capture: "🎙️ Nagre-record...", status_speak: "🔊 Nagsasalita...", tab_trans: "Isalin", tab_tutor: "Tutor", tab_admin: "Mga Setting", hint_encrypted: "Naka-encrypt na chat, lokal na history", btn_native_on: "💡 Bilingual Mode: On", btn_native_off: "💡 Bilingual Mode: Off", title_tutor: "👨‍🏫 AI Tutor", status_speak_tutor: "🔊 Nagsasalita (Pwedeng sumingit)..." },
    "fa": { title: "🗣️ مترجم", btn_start: "🎙️", status_sleep: "💤 آماده به کار", status_listen: "👂 در حال شنیدن...", status_capture: "🎙️ در حال ضبط...", status_speak: "🔊 در حال صحبت...", tab_trans: "ترجمه", tab_tutor: "معلم", tab_admin: "تنظیمات", hint_encrypted: "چت رمزگذاری شده، تاریخچه محلی", btn_native_on: "💡 حالت دوزبانه: روشن", btn_native_off: "💡 حالت دوزبانه: خاموش", title_tutor: "👨‍🏫 معلم هوش مصنوعی", status_speak_tutor: "🔊 در حال صحبت (امکان قطع)..." },
    "el": { title: "🗣️ Μεταφραστής", btn_start: "🎙️", status_sleep: "💤 Σε Αναμονή", status_listen: "👂 Ακούει...", status_capture: "🎙️ Εγγραφή...", status_speak: "🔊 Μιλάει...", tab_trans: "Μετάφραση", tab_tutor: "Καθηγητής", tab_admin: "Ρυθμίσεις", hint_encrypted: "Κρυπτογραφημένα, τοπικό ιστορικό", btn_native_on: "💡 Δίγλωσση Λειτουργία: On", btn_native_off: "💡 Δίγλωσση Λειτουργία: Off", title_tutor: "👨‍🏫 AI Καθηγητής", status_speak_tutor: "🔊 Μιλάει (Διακοπή δυνατή)..." },
    "hu": { title: "🗣️ Fordító", btn_start: "🎙️", status_sleep: "💤 Készenlét", status_listen: "👂 Figyelés...", status_capture: "🎙️ Felvétel...", status_speak: "🔊 Beszéd...", tab_trans: "Fordítás", tab_tutor: "Oktató", tab_admin: "Beállítások", hint_encrypted: "Titkosított chatek, helyi előzmények", btn_native_on: "💡 Kétnyelvű Mód: Be", btn_native_off: "💡 Kétnyelvű Mód: Ki", title_tutor: "👨‍🏫 AI Oktató", status_speak_tutor: "🔊 Beszéd (Félbeszakítható)..." },
    "mk": { title: "🗣️ Преведувач", btn_start: "🎙️", status_sleep: "💤 Подготвен", status_listen: "👂 Слушам...", status_capture: "🎙️ Снимам...", status_speak: "🔊 Зборувам...", tab_trans: "Преведи", tab_tutor: "Тутор", tab_admin: "Поставки", hint_encrypted: "Шифрирани разговори, локална историја", btn_native_on: "💡 Двојазичен Режим: Вкл", btn_native_off: "💡 Двојазичен Режим: Искл", title_tutor: "👨‍🏫 AI Тутор", status_speak_tutor: "🔊 Зборувам (Може да се прекине)..." },
    "ro": { title: "🗣️ Traducător", btn_start: "🎙️", status_sleep: "💤 În așteptare", status_listen: "👂 Ascultă...", status_capture: "🎙️ Înregistrare...", status_speak: "🔊 Vorbește...", tab_trans: "Traducere", tab_tutor: "Profesor", tab_admin: "Setări", hint_encrypted: "Chat criptat, istoric local", btn_native_on: "💡 Mod Bilingv: Pornit", btn_native_off: "💡 Mod Bilingv: Oprit", title_tutor: "👨‍🏫 Tutor AI", status_speak_tutor: "🔊 Vorbește (Poate fi întrerupt)..." }
};
// 暴露为全局挂载函数
window.applyUILanguage = function(langCode) {
    const dict = I18N_DICT[langCode] || I18N_DICT["en"] || I18N_DICT["zh"];
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (dict[key]) el.innerText = dict[key];
    });
    
    // 寻找页面中可能存在的动态状态按钮，如果处于休眠期则刷新文字
    const statusText = document.getElementById('statusText');
    if (statusText && statusText.innerText.includes('休眠') || statusText.innerText.includes('Asleep') || statusText.innerText.includes('Veille')) {
        statusText.innerText = dict["status_sleep"];
    }
};