// ==========================================
// 文件名: resources/i18n.js
// 架构定位: [Phase 5] 全局多语言静态字典与渲染引擎
// ==========================================

const SUPPORTED_LANGS = [
    {v: "zh", n: "中文 (zh)"}, {v: "en", n: "English (en)"}, {v: "yue", n: "粤语 (yue)"},
    {v: "ar", n: "العربية (ar)"}, {v: "de", n: "Deutsch (de)"}, {v: "fr", n: "Français (fr)"},
    {v: "es", n: "Español (es)"}, {v: "pt", n: "Português (pt)"}, {v: "id", n: "Bahasa Indonesia (id)"},
    {v: "it", n: "Italiano (it)"}, {v: "ko", n: "한국어 (ko)"}, {v: "ru", n: "Русский (ru)"},
    {v: "th", n: "ไทย (th)"}, {v: "vi", n: "Tiếng Việt (vi)"}, {v: "ja", n: "日本語 (ja)"},
    {v: "tr", n: "Türkçe (tr)"}, {v: "hi", n: "हिन्दी (hi)"}, {v: "ms", n: "Bahasa Melayu (ms)"},
    {v: "nl", n: "Nederlands (nl)"}, {v: "sv", n: "Svenska (sv)"}, {v: "da", n: "Dansk (da)"},
    {v: "fi", n: "Suomi (fi)"}, {v: "pl", n: "Polski (pl)"}, {v: "cs", n: "Čeština (cs)"},
    {v: "fil", n: "Filipino (fil)"}, {v: "fa", n: "فارسی (fa)"}, {v: "el", n: "Ελληνικά (el)"},
    {v: "hu", n: "Magyar (hu)"}, {v: "mk", n: "Македонски (mk)"}, {v: "ro", n: "Română (ro)"}
];

const I18N_DICT = {
    "zh": { title: "🗣️ 随身翻译", detecting: "环境语种: 待检测", btn_start: "🎙️", status_sleep: "系统已休眠", status_listen: "👂 倾听中...", status_capture: "🎙️ 捕获中...", status_speak: "🔊 正在播报...", tab_trans: "同传", tab_tutor: "外教", tab_admin: "设置", hint_encrypted: "对话已加密，历史记录仅保存在本地", btn_native_on: "💡 母语辅助: 开", btn_native_off: "💡 母语辅助: 关", title_tutor: "👨‍🏫 外教陪聊", status_speak_tutor: "🔊 发音中 (大声说话可打断)..." },
    "en": { title: "🗣️ Translator", detecting: "Env Lang: Detecting", btn_start: "🎙️", status_sleep: "System Asleep", status_listen: "👂 Listening...", status_capture: "🎙️ Capturing...", status_speak: "🔊 Speaking...", tab_trans: "Translate", tab_tutor: "Tutor", tab_admin: "Settings", hint_encrypted: "Chats encrypted, history saved locally", btn_native_on: "💡 Native Help: On", btn_native_off: "💡 Native Help: Off", title_tutor: "👨‍🏫 AI Tutor", status_speak_tutor: "🔊 Speaking (Barge-in)..." },
    "yue": { title: "🗣️ 隨身翻譯", detecting: "環境語言: 偵測中", btn_start: "🎙️", status_sleep: "系統已休眠", status_listen: "👂 聆聽中...", status_capture: "🎙️ 擷取中...", status_speak: "🔊 播放中...", tab_trans: "同傳", tab_tutor: "外教", tab_admin: "設定", hint_encrypted: "對話已加密，歷史記錄僅保存在本地", btn_native_on: "💡 母語輔助: 開", btn_native_off: "💡 母語輔助: 關", title_tutor: "👨‍🏫 外教陪傾", status_speak_tutor: "🔊 發音中 (大聲說話可打斷)..." },
    "ar": { title: "🗣️ المترجم", detecting: "لغة البيئة: جاري الكشف", btn_start: "🎙️", status_sleep: "وضع السكون", status_listen: "👂 يستمع...", status_capture: "🎙️ يسجل...", status_speak: "🔊 يتحدث...", tab_trans: "ترجمة", tab_tutor: "معلم", tab_admin: "إعدادات", hint_encrypted: "المحادثات مشفرة، السجل محلي", btn_native_on: "💡 مساعدة: تشغيل", btn_native_off: "💡 مساعدة: إيقاف", title_tutor: "👨‍🏫 المعلم الذكي", status_speak_tutor: "🔊 يتحدث (يمكنك المقاطعة)..." },
    "de": { title: "🗣️ Übersetzer", detecting: "Umgebung: Erkennung", btn_start: "🎙️", status_sleep: "Ruhezustand", status_listen: "👂 Hört zu...", status_capture: "🎙️ Nimmt auf...", status_speak: "🔊 Spricht...", tab_trans: "Übersetzen", tab_tutor: "Tutor", tab_admin: "Einst.", hint_encrypted: "Chats verschlüsselt, Verlauf lokal", btn_native_on: "💡 Muttersprache: An", btn_native_off: "💡 Muttersprache: Aus", title_tutor: "👨‍🏫 KI-Tutor", status_speak_tutor: "🔊 Spricht (Unterbrechen möglich)..." },
    "fr": { title: "🗣️ Traducteur", detecting: "Langue Env: Détection", btn_start: "🎙️", status_sleep: "En Veille", status_listen: "👂 Écoute...", status_capture: "🎙️ Capture...", status_speak: "🔊 Parle...", tab_trans: "Traduction", tab_tutor: "Prof", tab_admin: "Réglages", hint_encrypted: "Chats chiffrés, historique local", btn_native_on: "💡 Aide Maternelle: ON", btn_native_off: "💡 Aide Maternelle: OFF", title_tutor: "👨‍🏫 Prof IA", status_speak_tutor: "🔊 Parle (Interruption possible)..." },
    "es": { title: "🗣️ Traductor", detecting: "Idioma Env: Detectando", btn_start: "🎙️", status_sleep: "En Reposo", status_listen: "👂 Escuchando...", status_capture: "🎙️ Capturando...", status_speak: "🔊 Hablando...", tab_trans: "Traducir", tab_tutor: "Tutor", tab_admin: "Ajustes", hint_encrypted: "Chats cifrados, historial local", btn_native_on: "💡 Ayuda Nativa: ON", btn_native_off: "💡 Ayuda Nativa: OFF", title_tutor: "👨‍🏫 Tutor IA", status_speak_tutor: "🔊 Hablando (Interrumpir)..." },
    "pt": { title: "🗣️ Tradutor", detecting: "Idioma Amb: Detectando", btn_start: "🎙️", status_sleep: "Em Espera", status_listen: "👂 Ouvindo...", status_capture: "🎙️ Capturando...", status_speak: "🔊 Falando...", tab_trans: "Traduzir", tab_tutor: "Tutor", tab_admin: "Ajustes", hint_encrypted: "Chats criptografados, histórico local", btn_native_on: "💡 Ajuda Nativa: ON", btn_native_off: "💡 Ajuda Nativa: OFF", title_tutor: "👨‍🏫 Tutor IA", status_speak_tutor: "🔊 Falando (Pode interromper)..." },
    "id": { title: "🗣️ Penerjemah", detecting: "Bahasa: Mendeteksi", btn_start: "🎙️", status_sleep: "Sistem Tidur", status_listen: "👂 Mendengarkan...", status_capture: "🎙️ Menangkap...", status_speak: "🔊 Berbicara...", tab_trans: "Terjemahan", tab_tutor: "Tutor", tab_admin: "Pengaturan", hint_encrypted: "Obrolan dienkripsi, riwayat lokal", btn_native_on: "💡 Bantuan Bahasa: Nyala", btn_native_off: "💡 Bantuan Bahasa: Mati", title_tutor: "👨‍🏫 Tutor AI", status_speak_tutor: "🔊 Berbicara (Bisa disela)..." },
    "it": { title: "🗣️ Traduttore", detecting: "Lingua: Rilevamento", btn_start: "🎙️", status_sleep: "In Sospensione", status_listen: "👂 Ascoltando...", status_capture: "🎙️ Acquisizione...", status_speak: "🔊 Parlando...", tab_trans: "Traduci", tab_tutor: "Tutor", tab_admin: "Impost.", hint_encrypted: "Chat crittografate, cronologia locale", btn_native_on: "💡 Aiuto Madrelingua: ON", btn_native_off: "💡 Aiuto Madrelingua: OFF", title_tutor: "👨‍🏫 Tutor IA", status_speak_tutor: "🔊 Parlando (Interrompibile)..." },
    "ko": { title: "🗣️ 번역기", detecting: "언어: 감지 중", btn_start: "🎙️", status_sleep: "대기 중", status_listen: "👂 듣는 중...", status_capture: "🎙️ 녹음 중...", status_speak: "🔊 재생 중...", tab_trans: "번역", tab_tutor: "튜터", tab_admin: "설정", hint_encrypted: "대화 암호화됨, 기록 로컬 저장", btn_native_on: "💡 모국어 보조: 켜짐", btn_native_off: "💡 모국어 보조: 꺼짐", title_tutor: "👨‍🏫 AI 튜터", status_speak_tutor: "🔊 말하는 중 (끼어들기 가능)..." },
    "ru": { title: "🗣️ Переводчик", detecting: "Язык: Распознавание", btn_start: "🎙️", status_sleep: "Спящий режим", status_listen: "👂 Слушаю...", status_capture: "🎙️ Запись...", status_speak: "🔊 Говорю...", tab_trans: "Перевод", tab_tutor: "Репетитор", tab_admin: "Настройки", hint_encrypted: "Чаты зашифрованы, история локальна", btn_native_on: "💡 Родной язык: Вкл", btn_native_off: "💡 Родной язык: Выкл", title_tutor: "👨‍🏫 ИИ-Репетитор", status_speak_tutor: "🔊 Говорю (Можно перебить)..." },
    "th": { title: "🗣️ นักแปล", detecting: "ภาษา: กำลังตรวจจับ", btn_start: "🎙️", status_sleep: "โหมดสลีป", status_listen: "👂 กำลังฟัง...", status_capture: "🎙️ กำลังบันทึก...", status_speak: "🔊 กำลังพูด...", tab_trans: "แปล", tab_tutor: "ติวเตอร์", tab_admin: "ตั้งค่า", hint_encrypted: "แชทเข้ารหัส ประวัติถูกบันทึกในเครื่อง", btn_native_on: "💡 ช่วยเหลือภาษาแม่: เปิด", btn_native_off: "💡 ช่วยเหลือภาษาแม่: ปิด", title_tutor: "👨‍🏫 AI ติวเตอร์", status_speak_tutor: "🔊 กำลังพูด (พูดแทรกได้)..." },
    "vi": { title: "🗣️ Trình dịch", detecting: "Ngôn ngữ: Đang phát hiện", btn_start: "🎙️", status_sleep: "Đang ngủ", status_listen: "👂 Đang nghe...", status_capture: "🎙️ Đang thu...", status_speak: "🔊 Đang nói...", tab_trans: "Dịch", tab_tutor: "Gia sư", tab_admin: "Cài đặt", hint_encrypted: "Chat được mã hóa, lịch sử lưu cục bộ", btn_native_on: "💡 Trợ giúp bản ngữ: Bật", btn_native_off: "💡 Trợ giúp bản ngữ: Tắt", title_tutor: "👨‍🏫 Gia sư AI", status_speak_tutor: "🔊 Đang nói (Có thể ngắt lời)..." },
    "ja": { title: "🗣️ 翻訳機", detecting: "環境言語: 検出中", btn_start: "🎙️", status_sleep: "待機中", status_listen: "👂 リスニング...", status_capture: "🎙️ 録音中...", status_speak: "🔊 再生中...", tab_trans: "翻訳", tab_tutor: "講師", tab_admin: "設定", hint_encrypted: "チャット暗号化済、履歴はローカルのみ", btn_native_on: "💡 母国語補助: オン", btn_native_off: "💡 母国語補助: オフ", title_tutor: "👨‍🏫 AI 講師", status_speak_tutor: "🔊 再生中 (割り込み可能)..." },
    "tr": { title: "🗣️ Çevirmen", detecting: "Dil: Algılanıyor", btn_start: "🎙️", status_sleep: "Uyku Modu", status_listen: "👂 Dinleniyor...", status_capture: "🎙️ Kaydediliyor...", status_speak: "🔊 Konuşuluyor...", tab_trans: "Çeviri", tab_tutor: "Eğitmen", tab_admin: "Ayarlar", hint_encrypted: "Sohbetler şifreli, geçmiş yerel", btn_native_on: "💡 Ana Dil Yardımı: Açık", btn_native_off: "💡 Ana Dil Yardımı: Kapalı", title_tutor: "👨‍🏫 Yapay Zeka Eğitmeni", status_speak_tutor: "🔊 Konuşuluyor (Söze girilebilir)..." },
    "hi": { title: "🗣️ अनुवादक", detecting: "भाषा: पता लगा रहा है", btn_start: "🎙️", status_sleep: "स्लीप मोड", status_listen: "👂 सुन रहा है...", status_capture: "🎙️ कैप्चर कर रहा है...", status_speak: "🔊 बोल रहा है...", tab_trans: "अनुवाद", tab_tutor: "शिक्षक", tab_admin: "सेटिंग्स", hint_encrypted: "चैट एन्क्रिप्टेड, इतिहास स्थानीय", btn_native_on: "💡 मातृभाषा सहायता: चालू", btn_native_off: "💡 मातृभाषा सहायता: बंद", title_tutor: "👨‍🏫 AI ट्यूटर", status_speak_tutor: "🔊 बोल रहा है (बीच में टोकें)..." },
    "ms": { title: "🗣️ Penterjemah", detecting: "Bahasa: Mengesan", btn_start: "🎙️", status_sleep: "Tidur", status_listen: "👂 Mendengar...", status_capture: "🎙️ Menangkap...", status_speak: "🔊 Bercakap...", tab_trans: "Terjemah", tab_tutor: "Tutor", tab_admin: "Tetapan", hint_encrypted: "Sembang disulitkan, sejarah tempatan", btn_native_on: "💡 Bantuan Asli: Hidup", btn_native_off: "💡 Bantuan Asli: Mati", title_tutor: "👨‍🏫 Tutor AI", status_speak_tutor: "🔊 Bercakap (Boleh sampuk)..." },
    "nl": { title: "🗣️ Vertaler", detecting: "Taal: Detecteren", btn_start: "🎙️", status_sleep: "Slaapstand", status_listen: "👂 Luisteren...", status_capture: "🎙️ Opnemen...", status_speak: "🔊 Spreken...", tab_trans: "Vertalen", tab_tutor: "Docent", tab_admin: "Instellingen", hint_encrypted: "Chats versleuteld, lokale geschiedenis", btn_native_on: "💡 Moedertaal Hulp: Aan", btn_native_off: "💡 Moedertaal Hulp: Uit", title_tutor: "👨‍🏫 AI Docent", status_speak_tutor: "🔊 Spreken (Onderbreken)..." },
    "sv": { title: "🗣️ Översättare", detecting: "Språk: Detekterar", btn_start: "🎙️", status_sleep: "Viloläge", status_listen: "👂 Lyssnar...", status_capture: "🎙️ Spelar in...", status_speak: "🔊 Talar...", tab_trans: "Översätt", tab_tutor: "Lärare", tab_admin: "Inställningar", hint_encrypted: "Chattar krypterade, lokal historik", btn_native_on: "💡 Modersmålshjälp: På", btn_native_off: "💡 Modersmålshjälp: Av", title_tutor: "👨‍🏫 AI Lärare", status_speak_tutor: "🔊 Talar (Avbrytbar)..." },
    "da": { title: "🗣️ Oversætter", detecting: "Sprog: Detekterer", btn_start: "🎙️", status_sleep: "Dvale", status_listen: "👂 Lytter...", status_capture: "🎙️ Optager...", status_speak: "🔊 Taler...", tab_trans: "Oversæt", tab_tutor: "Tutor", tab_admin: "Indstillinger", hint_encrypted: "Chats krypteret, lokal historik", btn_native_on: "💡 Modersmål Hjælp: Til", btn_native_off: "💡 Modersmål Hjælp: Fra", title_tutor: "👨‍🏫 AI Tutor", status_speak_tutor: "🔊 Taler (Afbryd)..." },
    "fi": { title: "🗣️ Kääntäjä", detecting: "Kieli: Tunnistetaan", btn_start: "🎙️", status_sleep: "Lepotilassa", status_listen: "👂 Kuunnellaan...", status_capture: "🎙️ Nauhoitetaan...", status_speak: "🔊 Puhutaan...", tab_trans: "Käännä", tab_tutor: "Opettaja", tab_admin: "Asetukset", hint_encrypted: "Chatit salattu, paikallinen historia", btn_native_on: "💡 Äidinkieli Apu: Päällä", btn_native_off: "💡 Äidinkieli Apu: Pois", title_tutor: "👨‍🏫 AI Opettaja", status_speak_tutor: "🔊 Puhuu (Keskeytys)..." },
    "pl": { title: "🗣️ Tłumacz", detecting: "Język: Wykrywanie", btn_start: "🎙️", status_sleep: "W Uśpieniu", status_listen: "👂 Słuchanie...", status_capture: "🎙️ Nagrywanie...", status_speak: "🔊 Mówienie...", tab_trans: "Tłumacz", tab_tutor: "Nauczyciel", tab_admin: "Ustawienia", hint_encrypted: "Czaty zaszyfrowane, historia lokalna", btn_native_on: "💡 Pomoc Ojczysta: Wł", btn_native_off: "💡 Pomoc Ojczysta: Wył", title_tutor: "👨‍🏫 Nauczyciel AI", status_speak_tutor: "🔊 Mówi (Można przerwać)..." },
    "cs": { title: "🗣️ Překladatel", detecting: "Jazyk: Detekce", btn_start: "🎙️", status_sleep: "Režim Spánku", status_listen: "👂 Poslouchám...", status_capture: "🎙️ Nahrávání...", status_speak: "🔊 Mluvím...", tab_trans: "Překlad", tab_tutor: "Lektor", tab_admin: "Nastavení", hint_encrypted: "Chaty šifrovány, lokální historie", btn_native_on: "💡 Pomoc v Mateřštině: Zap", btn_native_off: "💡 Pomoc v Mateřštině: Vyp", title_tutor: "👨‍🏫 AI Lektor", status_speak_tutor: "🔊 Mluví (Lze přerušit)..." },
    "fil": { title: "🗣️ Tagasalin", detecting: "Wika: Tinutukoy", btn_start: "🎙️", status_sleep: "Natutulog", status_listen: "👂 Nakikinig...", status_capture: "🎙️ Nagre-record...", status_speak: "🔊 Nagsasalita...", tab_trans: "Isalin", tab_tutor: "Tutor", tab_admin: "Mga Setting", hint_encrypted: "Naka-encrypt na chat, lokal na history", btn_native_on: "💡 Tulong sa Sariling Wika: On", btn_native_off: "💡 Tulong sa Sariling Wika: Off", title_tutor: "👨‍🏫 AI Tutor", status_speak_tutor: "🔊 Nagsasalita (Sumingit)..." },
    "fa": { title: "🗣️ مترجم", detecting: "زبان: تشخیص", btn_start: "🎙️", status_sleep: "حالت خواب", status_listen: "👂 در حال شنیدن...", status_capture: "🎙️ در حال ضبط...", status_speak: "🔊 در حال صحبت...", tab_trans: "ترجمه", tab_tutor: "معلم", tab_admin: "تنظیمات", hint_encrypted: "چت رمزگذاری شده، تاریخچه محلی", btn_native_on: "💡 کمک زبان مادری: روشن", btn_native_off: "💡 کمک زبان مادری: خاموش", title_tutor: "👨‍🏫 معلم هوش مصنوعی", status_speak_tutor: "🔊 در حال صحبت (امکان قطع)..." },
    "el": { title: "🗣️ Μεταφραστής", detecting: "Γλώσσα: Ανίχνευση", btn_start: "🎙️", status_sleep: "Σε Αναστολή", status_listen: "👂 Ακούει...", status_capture: "🎙️ Καταγράφει...", status_speak: "🔊 Μιλάει...", tab_trans: "Μετάφραση", tab_tutor: "Καθηγητής", tab_admin: "Ρυθμίσεις", hint_encrypted: "Κρυπτογραφημένα, τοπικό ιστορικό", btn_native_on: "💡 Βοήθεια Μητρικής: On", btn_native_off: "💡 Βοήθεια Μητρικής: Off", title_tutor: "👨‍🏫 AI Καθηγητής", status_speak_tutor: "🔊 Μιλάει (Διακοπή)..." },
    "hu": { title: "🗣️ Fordító", detecting: "Nyelv: Észlelés", btn_start: "🎙️", status_sleep: "Alvó Mód", status_listen: "👂 Figyelés...", status_capture: "🎙️ Rögzítés...", status_speak: "🔊 Beszéd...", tab_trans: "Fordítás", tab_tutor: "Oktató", tab_admin: "Beállítások", hint_encrypted: "Titkosított chatek, helyi előzmények", btn_native_on: "💡 Anyanyelvi Súgó: Be", btn_native_off: "💡 Anyanyelvi Súgó: Ki", title_tutor: "👨‍🏫 AI Oktató", status_speak_tutor: "🔊 Beszéd (Félbeszakítható)..." },
    "mk": { title: "🗣️ Преведувач", detecting: "Јазик: Детектирање", btn_start: "🎙️", status_sleep: "Мирување", status_listen: "👂 Слушам...", status_capture: "🎙️ Снимам...", status_speak: "🔊 Зборувам...", tab_trans: "Преведи", tab_tutor: "Тутор", tab_admin: "Поставки", hint_encrypted: "Шифрирани разговори, локална историја", btn_native_on: "💡 Мајчин јазик: Вкл", btn_native_off: "💡 Мајчин јазик: Искл", title_tutor: "👨‍🏫 AI Тутор", status_speak_tutor: "🔊 Зборувам (Може да прекинете)..." },
    "ro": { title: "🗣️ Traducător", detecting: "Limba: Detectare", btn_start: "🎙️", status_sleep: "În Așteptare", status_listen: "👂 Ascultă...", status_capture: "🎙️ Capturează...", status_speak: "🔊 Vorbește...", tab_trans: "Traducere", tab_tutor: "Profesor", tab_admin: "Setări", hint_encrypted: "Chat criptat, istoric local", btn_native_on: "💡 Ajutor Matern: Pornit", btn_native_off: "💡 Ajutor Matern: Oprit", title_tutor: "👨‍🏫 Tutor AI", status_speak_tutor: "🔊 Vorbește (Poate fi întrerupt)..." }
};

// 暴露为全局挂载函数
window.applyUILanguage = function(langCode) {
    const dict = I18N_DICT[langCode] || I18N_DICT["en"] || I18N_DICT["zh"];
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (dict[key]) el.innerText = dict[key];
    });
    
    // 寻找页面中可能存在的动态状态按钮，如果处于休眠期则刷新文字
    const statusText = document.getElementById('statusText');
    if (statusText && statusText.innerText.includes('休眠') || statusText.innerText.includes('Asleep') || statusText.innerText.includes('Veille')) {
        statusText.innerText = dict["status_sleep"];
    }
};